export const ENV_VAR_NAMES = {
  NODE_ENV: "NODE_ENV",

  OPENAI_API_KEY: "OPENAI_API_KEY",
  ANTHROPIC_API_KEY: "ANTHROPIC_API_KEY",
  MISTRAL_API_KEY: "MISTRAL_API_KEY",
  GOOGLE_API_KEY: "GOOGLE_API_KEY",
  TAVILY_API_KEY: "TAVILY_API_KEY",

  OLLAMA_BASE_URL: "OLLAMA_BASE_URL",

  SHIPSPEC_LOAD_DOTENV: "SHIPSPEC_LOAD_DOTENV",
  SHIPSPEC_DOTENV_OVERRIDE: "SHIPSPEC_DOTENV_OVERRIDE",
  SHIPSPEC_DOTENV_OVERRIDE_ACK: "SHIPSPEC_DOTENV_OVERRIDE_ACK",
  SHIPSPEC_DOTENV_PATH: "SHIPSPEC_DOTENV_PATH",

  SHIPSPEC_STRICT_CONFIG: "SHIPSPEC_STRICT_CONFIG",

  SHIPSPEC_DEBUG_DIAGNOSTICS: "SHIPSPEC_DEBUG_DIAGNOSTICS",
  ALLOW_LOCALHOST_LLM: "ALLOW_LOCALHOST_LLM",
} as const;

export const ALL_ENV_VARS = Object.values(ENV_VAR_NAMES);

export const CONDITIONAL_REQUIRED_VARS = {
  OPENAI_API_KEY: ["llm.provider=openai", "embedding.provider=openai"],
  TAVILY_API_KEY: ["productionalize.webSearch.provider=tavily"],
  SHIPSPEC_DOTENV_PATH: ["NODE_ENV=production && SHIPSPEC_LOAD_DOTENV=1"],
  SHIPSPEC_DOTENV_OVERRIDE_ACK: ["NODE_ENV=production && SHIPSPEC_DOTENV_OVERRIDE=1"],
} as const;
