export const ENV_VAR_NAMES = {
  NODE_ENV: "NODE_ENV",

  OPENROUTER_API_KEY: "OPENROUTER_API_KEY",
  TAVILY_API_KEY: "TAVILY_API_KEY",

  OLLAMA_BASE_URL: "OLLAMA_BASE_URL",

  SHIPSPEC_LOAD_DOTENV: "SHIPSPEC_LOAD_DOTENV",
  SHIPSPEC_DOTENV_OVERRIDE: "SHIPSPEC_DOTENV_OVERRIDE",
  SHIPSPEC_DOTENV_OVERRIDE_ACK: "SHIPSPEC_DOTENV_OVERRIDE_ACK",
  SHIPSPEC_DOTENV_PATH: "SHIPSPEC_DOTENV_PATH",

  SHIPSPEC_STRICT_CONFIG: "SHIPSPEC_STRICT_CONFIG",

  SHIPSPEC_DEBUG_DIAGNOSTICS: "SHIPSPEC_DEBUG_DIAGNOSTICS",
  SHIPSPEC_DEBUG_DIAGNOSTICS_ACK: "SHIPSPEC_DEBUG_DIAGNOSTICS_ACK",
  ALLOW_LOCALHOST_LLM: "ALLOW_LOCALHOST_LLM",
} as const;

export const ALL_ENV_VARS = Object.values(ENV_VAR_NAMES);

export const CONDITIONAL_REQUIRED_VARS = {
  OPENROUTER_API_KEY: ["llm.provider=openrouter", "embedding.provider=openrouter"],
  TAVILY_API_KEY: ["productionalize.webSearch.provider=tavily"],
  SHIPSPEC_DOTENV_PATH: ["NODE_ENV=production && SHIPSPEC_LOAD_DOTENV=1"],
  SHIPSPEC_DOTENV_OVERRIDE_ACK: ["NODE_ENV=production && SHIPSPEC_DOTENV_OVERRIDE=1"],
} as const;
